version: '3.8'

services:
  # Frontend Development Server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - quantum-network

  # Backend API Server
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://quantum_user:quantum_pass@postgres:5432/quantum_db
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - MAXIMO_OAUTH_CLIENT_ID=your-maximo-client-id
      - MAXIMO_OAUTH_CLIENT_SECRET=your-maximo-client-secret
      - MAXIMO_BASE_URL=https://your-maximo-instance.com
    depends_on:
      - redis
      - postgres
    networks:
      - quantum-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - quantum-network

  # PostgreSQL database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quantum_db
      - POSTGRES_USER=quantum_user
      - POSTGRES_PASSWORD=quantum_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quantum-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - quantum-network

volumes:
  redis_data:
  postgres_data:

networks:
  quantum-network:
    driver: bridge